version: '3'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile_local
    volumes:
      - ./web_project:/app
    working_dir: /app
    user: '1000:1000'
    ports:
      - 8000:8000
    command: bash -c "composer install && php -S 0.0.0.0:8000 -t /app"

