---
- name: Развёртывание веб-проекта
  hosts: all
  become: true
  vars_files: www-data/vars.yml

  tasks:
    - name: Обновление кеша APT
      apt:
        update_cache: yes
    
    - name: Установка зависимостей
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
          - python3-pip
        state: present

    - name: Добавление ключа GPG Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Добавление репозитория Docker
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Установка Docker
      apt:
        name: docker-ce
        state: present

    - name: Установка Docker Compose
      shell: curl -sSL https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64 -o /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose
      args:
        creates: /usr/local/bin/docker-compose

    - name: Перезапуск службы Docker
      systemd:
        name: docker
        state: restarted

    - name: Создание дирректории для хранения файлов веб-проекта
      file:
        path: '{{ path_for_project }}'
        state: directory
        mode: '0755'

    - name: Копирование веб-проекта в созданную дирректорию
      copy:
        src: web_project
        dest: '{{ path_for_project }}'

    - name: Копирования файлов для запуска веб-проекта в контейнере
      copy:
        src: '{{ item }}'
        dest: '{{ path_for_project }}'
      loop:
        - docker-compose.yml
        - Dockerfile

    - name: Pip install docker-compose
      pip: 
        name: docker-compose
    
    - name: Сборка и запуск веб-проекта в docker
      docker_compose:
        project_src: '{{ path_for_project }}'
        files:
          - docker-compose.yml 
      

