name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install ssh-agent
        uses: webfactory/ssh-agent@v0.4.1

      - name: Add SSH private key
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}" | ssh-add -

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo apt-add-repository ppa:ansible/ansible
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Run ansible playbook
        run: |
          ansible-playbook -i inventory.yml playbook.yml
