name: Build and push Docker image

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-push:
    name: Build and push Docker image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: your-dockerhub-username/my-image:${{ github.sha }}
        builder: |
          FROM php:8-cli
          COPY ./web_project /usr/src/myapp
          WORKDIR /usr/src/myapp

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker image to Docker Hub
      run: docker push your-dockerhub-username/my-image:${{ github.sha }}
